services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'cmkau'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'sample_food_auth'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - C:\Users\cmkau\sample-food-auth\mysql:/var/lib/mysql